"""Batch data insertion with multi-database support."""

import json
import datetime
import decimal
import uuid as uuid_mod

from seedforge.introspector import TableInfo


class BatchInserter:
    BATCH_SIZE = 500

    def __init__(self, connection, engine: str = "PostgreSQL"):
        self.connection = connection
        self.engine = engine.lower()
        self._is_mysql = self.engine in ("mysql", "mariadb")
        self._is_sqlite = self.engine == "sqlite"
        self._q = "`" if self._is_mysql else '"'

    def insert_all(
        self,
        data: dict[str, list[dict]],
        tables: dict[str, TableInfo],
        order: list[str],
    ):
        """Insert all data in topological order."""
        old_autocommit = getattr(self.connection, 'autocommit', None)
        if old_autocommit is not None:
            self.connection.autocommit = False

        try:
            cur = self.connection.cursor()
            q = self._q

            for table_name in order:
                rows = data.get(table_name, [])
                if not rows:
                    continue

                columns = list(rows[0].keys())
                col_list = ", ".join(f'{q}{c}{q}' for c in columns)
                placeholders = ", ".join(["%s"] * len(columns))

                for i in range(0, len(rows), self.BATCH_SIZE):
                    batch = rows[i:i + self.BATCH_SIZE]
                    values = [
                        tuple(self._prep_value(row.get(c)) for c in columns)
                        for row in batch
                    ]

                    if self._is_sqlite:
                        ph = ", ".join(["?"] * len(columns))
                        sql = f'INSERT INTO {q}{table_name}{q} ({col_list}) VALUES ({ph})'
                        cur.executemany(sql, values)
                    elif self._is_mysql:
                        sql = f'INSERT INTO {q}{table_name}{q} ({col_list}) VALUES ({placeholders})'
                        cur.executemany(sql, values)
                    else:
                        from psycopg2.extras import execute_values
                        template = "(" + ", ".join(["%s"] * len(columns)) + ")"
                        sql = f'INSERT INTO {q}{table_name}{q} ({col_list}) VALUES %s'
                        execute_values(cur, sql, values, template=template)

            self.connection.commit()
            cur.close()
        except Exception:
            self.connection.rollback()
            raise
        finally:
            if old_autocommit is not None:
                self.connection.autocommit = old_autocommit

    def truncate_tables(self, order: list[str]):
        """Truncate tables in reverse order (children first)."""
        q = self._q
        cur = self.connection.cursor()
        if self._is_mysql:
            cur.execute("SET FOREIGN_KEY_CHECKS = 0")
            for table_name in reversed(order):
                cur.execute(f'TRUNCATE TABLE {q}{table_name}{q}')
            cur.execute("SET FOREIGN_KEY_CHECKS = 1")
        else:
            for table_name in reversed(order):
                cur.execute(f'TRUNCATE TABLE {q}{table_name}{q} CASCADE')
        cur.close()

    @staticmethod
    def generate_sql(
        data: dict[str, list[dict]],
        tables: dict[str, TableInfo],
        order: list[str],
        engine: str = "PostgreSQL",
    ) -> str:
        """Generate SQL file with INSERT statements."""
        is_mysql = engine.lower() in ("mysql", "mariadb")
        q = "`" if is_mysql else '"'

        lines = ["-- Generated by SeedForge", "-- https://github.com/silkhorizonstudios/seedforge", ""]
        if is_mysql:
            lines.append("SET FOREIGN_KEY_CHECKS = 0;")
        lines.append("BEGIN;")
        lines.append("")

        for table_name in order:
            rows = data.get(table_name, [])
            if not rows:
                continue

            columns = list(rows[0].keys())
            col_list = ", ".join(f'{q}{c}{q}' for c in columns)

            lines.append(f"-- {table_name} ({len(rows)} rows)")

            for row in rows:
                values = ", ".join(
                    BatchInserter._sql_value(row.get(c)) for c in columns
                )
                lines.append(f'INSERT INTO {q}{table_name}{q} ({col_list}) VALUES ({values});')

            lines.append("")

        lines.append("COMMIT;")
        if is_mysql:
            lines.append("SET FOREIGN_KEY_CHECKS = 1;")
        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _prep_value(value):
        """Prepare value for the DB driver."""
        if value is None:
            return None
        if isinstance(value, dict):
            return json.dumps(value)
        return value

    @staticmethod
    def _sql_value(value) -> str:
        """Convert value to SQL literal."""
        if value is None:
            return "NULL"
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        if isinstance(value, (int, float, decimal.Decimal)):
            return str(value)
        if isinstance(value, (datetime.date, datetime.datetime)):
            return f"'{value.isoformat()}'"
        if isinstance(value, uuid_mod.UUID):
            return f"'{value}'"
        if isinstance(value, dict):
            escaped = json.dumps(value).replace("'", "''")
            return f"'{escaped}'"
        if isinstance(value, bytes):
            return f"'\\x{value.hex()}'"
        escaped = str(value).replace("'", "''")
        return f"'{escaped}'"
