"""Batch INSERT данных в PostgreSQL."""

import json
import datetime
import decimal
import uuid as uuid_mod
from psycopg2.extras import execute_values

from seedforge.introspector import TableInfo


class BatchInserter:
    BATCH_SIZE = 500

    def __init__(self, connection):
        self.connection = connection

    def insert_all(
        self,
        data: dict[str, list[dict]],
        tables: dict[str, TableInfo],
        order: list[str],
    ):
        """Вставить все данные в порядке topological sort."""
        # Отключаем autocommit для транзакции
        old_autocommit = self.connection.autocommit
        self.connection.autocommit = False

        try:
            cur = self.connection.cursor()

            for table_name in order:
                rows = data.get(table_name, [])
                if not rows:
                    continue

                columns = list(rows[0].keys())
                col_list = ", ".join(f'"{c}"' for c in columns)

                # Batch INSERT через execute_values
                template = "(" + ", ".join(["%s"] * len(columns)) + ")"

                for i in range(0, len(rows), self.BATCH_SIZE):
                    batch = rows[i:i + self.BATCH_SIZE]
                    values = [
                        tuple(self._prep_value(row.get(c)) for c in columns)
                        for row in batch
                    ]
                    sql = f'INSERT INTO "{table_name}" ({col_list}) VALUES %s'

                    try:
                        execute_values(cur, sql, values, template=template)
                    except Exception as e:
                        self.connection.rollback()
                        raise RuntimeError(f"Insert into {table_name} failed: {e}") from e

            self.connection.commit()
            cur.close()
        finally:
            self.connection.autocommit = old_autocommit

    def truncate_tables(self, order: list[str]):
        """TRUNCATE таблицы в обратном порядке (дети первые)."""
        cur = self.connection.cursor()
        for table_name in reversed(order):
            cur.execute(f'TRUNCATE TABLE "{table_name}" CASCADE')
        cur.close()

    @staticmethod
    def generate_sql(
        data: dict[str, list[dict]],
        tables: dict[str, TableInfo],
        order: list[str],
    ) -> str:
        """Генерация SQL-файла с INSERT-ами."""
        lines = ["-- Generated by SeedForge", "-- https://github.com/silkhorizon/seedforge", ""]
        lines.append("BEGIN;")
        lines.append("")

        for table_name in order:
            rows = data.get(table_name, [])
            if not rows:
                continue

            columns = list(rows[0].keys())
            col_list = ", ".join(f'"{c}"' for c in columns)

            lines.append(f"-- {table_name} ({len(rows)} rows)")

            for row in rows:
                values = ", ".join(
                    BatchInserter._sql_value(row.get(c)) for c in columns
                )
                lines.append(f'INSERT INTO "{table_name}" ({col_list}) VALUES ({values});')

            lines.append("")

        lines.append("COMMIT;")
        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _prep_value(value):
        """Подготовить значение для psycopg2."""
        if value is None:
            return None
        if isinstance(value, dict):
            return json.dumps(value)
        if isinstance(value, bytes):
            return value
        return value

    @staticmethod
    def _sql_value(value) -> str:
        """Конвертировать значение в SQL-литерал."""
        if value is None:
            return "NULL"
        if isinstance(value, bool):
            return "TRUE" if value else "FALSE"
        if isinstance(value, (int, float, decimal.Decimal)):
            return str(value)
        if isinstance(value, (datetime.date, datetime.datetime)):
            return f"'{value.isoformat()}'"
        if isinstance(value, uuid_mod.UUID):
            return f"'{value}'"
        if isinstance(value, dict):
            escaped = json.dumps(value).replace("'", "''")
            return f"'{escaped}'"
        if isinstance(value, bytes):
            return f"'\\x{value.hex()}'"
        # String — escape single quotes
        escaped = str(value).replace("'", "''")
        return f"'{escaped}'"
